# -*- coding: utf-8 -*-
"""TAKD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WtygtXud7NB0vPePtmswPIsLtnFaQoAW
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive

!git clone https://github.com/imirzadeh/Teacher-Assistant-Knowledge-Distillation.git

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Teacher-Assistant-Knowledge-Distillation

!mkdir -p /content/drive/MyDrive/TAKD_models

!python train.py --epochs 80 --student plane2 --dataset cifar10 --learning-rate 0.1 --momentum 0.9 --weight-decay 0.0001 --cuda true

!python train.py --epochs 80 --student plane2 --dataset cifar10 --learning-rate 0.01 --momentum 0.9 --weight-decay 0.0001 --cuda true

!cp /content/drive/MyDrive/TAKD_models/plane2_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/cnn_cifar10_nokd_plane2_best.pth.tar

!python train.py --epochs 70 --teacher plane10 --student plane2 --dataset cifar10 --learning-rate 0.01 --momentum 0.9 --weight-decay 0.0001 --cuda true

!cp /content/drive/MyDrive/TAKD_models/plane10_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/cnn_cifar10_teacher_plane10_best.pth.tar
!cp /content/drive/MyDrive/TAKD_models/plane2_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/cnn_cifar10_blkd_plane2_best.pth.tar

!python train.py --epochs 80 --teacher plane10 --teacher-checkpoint /content/drive/MyDrive/TAKD_models/cnn_cifar10_teacher_plane10_best.pth.tar --student plane4 --dataset cifar10 --learning-rate 0.01 --momentum 0.9 --weight-decay 0.0001 --cuda true

!cp /content/drive/MyDrive/TAKD_models/plane4_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/cnn_cifar10_ta_plane4_best.pth.tar

!python train.py --epochs 80 --teacher plane4 --teacher-checkpoint /content/drive/MyDrive/TAKD_models/cnn_cifar10_ta_plane4_best.pth.tar --student plane2 --dataset cifar10 --learning-rate 0.01 --momentum 0.9 --weight-decay 0.0001 --cuda true

!cp /content/drive/MyDrive/TAKD_models/plane2_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/cnn_cifar10_takd_plane2_best.pth.tar

!python train.py --epochs 80 --student resnet8 --dataset cifar10 --learning-rate 0.1 --momentum 0.9 --weight-decay 0.0001 --cuda true

!cp /content/drive/MyDrive/TAKD_models/resnet8_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/resnet_cifar10_nokd_resnet8_best.pth.tar

import torch
from data_loader import get_cifar
from model_factory import create_cnn_model

device = "cuda" if torch.cuda.is_available() else "cpu"

def evaluate(model_name, path):
    _, test_loader = get_cifar(10)
    model = create_cnn_model(model_name, "cifar10", use_cuda=(device=="cuda"))

    ckpt = torch.load(path, map_location=device)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()

    correct, total = 0, 0
    with torch.no_grad():
        for x, y in test_loader:
            x, y = x.to(device), y.to(device)
            out = model(x)
            _, pred = torch.max(out, 1)
            total += y.size(0)
            correct += (pred == y).sum().item()

    acc = 100 * correct / total
    print(f"{path.split('/')[-1]} → {acc:.2f}%")

base = "/content/drive/MyDrive/TAKD_models/"

evaluate("plane2", base + "cnn_cifar10_nokd_plane2_best.pth.tar")
evaluate("plane2", base + "cnn_cifar10_blkd_plane2_best.pth.tar")
evaluate("plane2", base + "cnn_cifar10_takd_plane2_best.pth.tar")

!python train.py --epochs 70 --teacher resnet110 --student resnet8 --dataset cifar10 --learning-rate 0.1 --momentum 0.9 --weight-decay 0.0001 --cuda true

!cp /content/drive/MyDrive/TAKD_models/resnet110_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/resnet_cifar10_teacher_resnet110_best.pth.tar
!cp /content/drive/MyDrive/TAKD_models/resnet8_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/resnet_cifar10_blkd_resnet8_best.pth.tar

!cp /content/drive/MyDrive/TAKD_models/resnet20_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/resnet_cifar10_ta_resnet20_best.pth.tar

!cp /content/drive/MyDrive/TAKD_models/resnet8_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/resnet_cifar10_takd_resnet8_best.pth.tar

!ls /content/drive/MyDrive/TAKD_models

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Teacher-Assistant-Knowledge-Distillation

!ls /content/drive/MyDrive/TAKD_models | grep resnet_cifar10

!rm -f /content/drive/MyDrive/TAKD_models/resnet_cifar10_*
!rm -f /content/drive/MyDrive/TAKD_models/resnet8_manual_best.pth.tar
!rm -f /content/drive/MyDrive/TAKD_models/resnet20_manual_best.pth.tar
!rm -f /content/drive/MyDrive/TAKD_models/resnet110_manual_best.pth.tar

!python train.py --epochs 70 --student resnet8 --dataset cifar10 --learning-rate 0.1 --momentum 0.9 --weight-decay 0.0001 --cuda true

!cp /content/drive/MyDrive/TAKD_models/resnet8_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/resnet_cifar10_nokd_resnet8_best.pth.tar

!python train.py --epochs 60 --teacher resnet110 --student resnet8 --dataset cifar10 --learning-rate 0.1 --momentum 0.9 --weight-decay 0.0001 --cuda true

!cp /content/drive/MyDrive/TAKD_models/resnet110_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/resnet_cifar10_teacher_resnet110_best.pth.tar
!cp /content/drive/MyDrive/TAKD_models/resnet8_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/resnet_cifar10_blkd_resnet8_best.pth.tar

!python train.py --epochs 70 --teacher resnet110 --teacher-checkpoint /content/drive/MyDrive/TAKD_models/resnet_cifar10_teacher_resnet110_best.pth.tar --student resnet20 --dataset cifar10 --learning-rate 0.1 --momentum 0.9 --weight-decay 0.0001 --cuda true

!cp /content/drive/MyDrive/TAKD_models/resnet20_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/resnet_cifar10_ta_resnet20_best.pth.tar

!python train.py --epochs 70 --teacher resnet20 --teacher-checkpoint /content/drive/MyDrive/TAKD_models/resnet_cifar10_ta_resnet20_best.pth.tar --student resnet8 --dataset cifar10 --learning-rate 0.1 --momentum 0.9 --weight-decay 0.0001 --cuda true

!cp /content/drive/MyDrive/TAKD_models/resnet8_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/resnet_cifar10_takd_resnet8_best.pth.tar

!ls /content/drive/MyDrive/TAKD_models | grep resnet_cifar10
import torch
from data_loader import get_cifar
from model_factory import create_cnn_model

device = "cuda" if torch.cuda.is_available() else "cpu"

def evaluate(model_name, path):
    _, test_loader = get_cifar(10)
    model = create_cnn_model(model_name, "cifar10", use_cuda=(device == "cuda"))

    ckpt = torch.load(path, map_location=device)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()

    correct, total = 0, 0
    with torch.no_grad():
        for x, y in test_loader:
            x, y = x.to(device), y.to(device)
            out = model(x)
            _, pred = torch.max(out, 1)
            total += y.size(0)
            correct += (pred == y).sum().item()

    acc = 100 * correct / total
    print(f"{path.split('/')[-1]} → {acc:.2f}%")

base = "/content/drive/MyDrive/TAKD_models/"

evaluate("resnet8", base + "resnet_cifar10_nokd_resnet8_best.pth.tar")
evaluate("resnet8", base + "resnet_cifar10_blkd_resnet8_best.pth.tar")
evaluate("resnet8", base + "resnet_cifar10_takd_resnet8_best.pth.tar")

from google.colab import drive
drive.mount('/content/drive')

!rm -f /content/drive/MyDrive/TAKD_models/cnn_cifar100_*
!rm -f /content/drive/MyDrive/TAKD_models/plane2_manual_best.pth.tar
!rm -f /content/drive/MyDrive/TAKD_models/plane4_manual_best.pth.tar
!rm -f /content/drive/MyDrive/TAKD_models/plane10_manual_best.pth.tar

!python train.py --epochs 80 --student plane2 --dataset cifar100 --learning-rate 0.01 --momentum 0.9 --weight-decay 0.0001 --cuda true
!cp /content/drive/MyDrive/TAKD_models/plane2_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/cnn_cifar100_nokd_plane2_best.pth.tar

!python train.py --epochs 80 --teacher plane10 --student plane2 --dataset cifar100 --learning-rate 0.01 --momentum 0.9 --weight-decay 0.0001 --cuda true
!cp /content/drive/MyDrive/TAKD_models/plane10_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/cnn_cifar100_teacher_plane10_best.pth.tar
!cp /content/drive/MyDrive/TAKD_models/plane2_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/cnn_cifar100_blkd_plane2_best.pth.tar

!python train.py --epochs 80 --teacher plane10 --teacher-checkpoint /content/drive/MyDrive/TAKD_models/cnn_cifar100_teacher_plane10_best.pth.tar --student plane4 --dataset cifar100 --learning-rate 0.01 --momentum 0.9 --weight-decay 0.0001 --cuda true

from google.colab import drive
drive.mount('/content/drive')

!cp /content/drive/MyDrive/TAKD_models/plane4_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/cnn_cifar100_ta_plane4_best.pth.tar

!python train.py --epochs 80 --teacher plane4 --teacher-checkpoint /content/drive/MyDrive/TAKD_models/cnn_cifar100_ta_plane4_best.pth.tar --student plane2 --dataset cifar100 --learning-rate 0.01 --momentum 0.9 --weight-decay 0.0001 --cuda true
!cp /content/drive/MyDrive/TAKD_models/plane2_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/cnn_cifar100_takd_plane2_best.pth.tar

import torch
from data_loader import get_cifar
from model_factory import create_cnn_model

device = "cuda" if torch.cuda.is_available() else "cpu"

def evaluate(model_name, path, dataset):
    num_classes = 100 if dataset == "cifar100" else 10
    _, test_loader = get_cifar(num_classes)
    model = create_cnn_model(model_name, dataset, use_cuda=(device == "cuda"))

    ckpt = torch.load(path, map_location=device)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()

    correct, total = 0, 0
    with torch.no_grad():
        for x, y in test_loader:
            x, y = x.to(device), y.to(device)
            out = model(x)
            _, pred = torch.max(out, 1)
            total += y.size(0)
            correct += (pred == y).sum().item()

    acc = 100 * correct / total
    print(f"{path.split('/')[-1]} → {acc:.2f}%")

base = "/content/drive/MyDrive/TAKD_models/"

evaluate("plane2", base + "cnn_cifar100_nokd_plane2_best.pth.tar", "cifar100")
evaluate("plane2", base + "cnn_cifar100_blkd_plane2_best.pth.tar", "cifar100")
evaluate("plane2", base + "cnn_cifar100_takd_plane2_best.pth.tar", "cifar100")

!rm -f /content/drive/MyDrive/TAKD_models/resnet_cifar100_*
!rm -f /content/drive/MyDrive/TAKD_models/resnet8_manual_best.pth.tar
!rm -f /content/drive/MyDrive/TAKD_models/resnet20_manual_best.pth.tar
!rm -f /content/drive/MyDrive/TAKD_models/resnet110_manual_best.pth.tar

!python train.py --epochs 80 --student resnet8 --dataset cifar100 --learning-rate 0.1 --momentum 0.9 --weight-decay 0.0001 --cuda true
!cp /content/drive/MyDrive/TAKD_models/resnet8_manual_best.pth.tar /content/drive/MyDrive/TAKD_models/resnet_cifar100_nokd_resnet8_best.pth.tar

!python train.py --epochs 60 --student resnet110 --dataset cifar100 --learning-rate 0.1 --momentum 0.9 --weight-decay 0.0001 --cuda true
!cp /content/drive/MyDrive/TAKD_models/resnet110_manual_best.pth.tar \
/content/drive/MyDrive/TAKD_models/resnet_cifar100_teacher_resnet110_best.pth.tar

!python train.py \
--epochs 60 \
--teacher resnet110 \
--teacher-checkpoint /content/drive/MyDrive/TAKD_models/resnet_cifar100_teacher_resnet110_best.pth.tar \
--student resnet8 \
--dataset cifar100 \
--learning-rate 0.1 \
--momentum 0.9 \
--weight-decay 0.0001 \
--cuda true

!cp /content/drive/MyDrive/TAKD_models/resnet8_manual_best.pth.tar \
/content/drive/MyDrive/TAKD_models/resnet_cifar100_blkd_resnet8_best.pth.tar

!ls /content/drive/MyDrive/TAKD_models | grep resnet_cifar100

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Teacher-Assistant-Knowledge-Distillation

import os
import torch
from data_loader import get_cifar
from model_factory import create_cnn_model

device = "cuda" if torch.cuda.is_available() else "cpu"

def evaluate(model_name, path, dataset="cifar100"):
    if not os.path.exists(path):
        print(f"Missing: {path}")
        return None

    num_classes = 100 if dataset == "cifar100" else 10
    _, test_loader = get_cifar(num_classes)

    model = create_cnn_model(model_name, dataset, use_cuda=(device == "cuda"))
    ckpt = torch.load(path, map_location=device)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()

    correct = 0
    total = 0
    with torch.no_grad():
        for x, y in test_loader:
            x, y = x.to(device), y.to(device)
            out = model(x)
            _, pred = torch.max(out, 1)
            total += y.size(0)
            correct += (pred == y).sum().item()

    acc = 100.0 * correct / total
    print(f"{os.path.basename(path)} -> {acc:.2f}%")
    return acc

base = "/content/drive/MyDrive/TAKD_models/"

files_to_check = [
    ("resnet8", base + "resnet_cifar100_nokd_resnet8_best.pth.tar"),
    ("resnet8", base + "resnet_cifar100_blkd_resnet8_best.pth.tar"),
    ("resnet8", base + "resnet_cifar100_takd_resnet8_best.pth.tar"),
    ("resnet110", base + "resnet_cifar100_teacher_resnet110_best.pth.tar"),
    ("resnet20", base + "resnet_cifar100_ta_resnet20_best.pth.tar"),
]

for model_name, path in files_to_check:
    evaluate(model_name, path, dataset="cifar100")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Teacher-Assistant-Knowledge-Distillation

import os
import torch
import pandas as pd
from data_loader import get_cifar
from model_factory import create_cnn_model

device = "cuda" if torch.cuda.is_available() else "cpu"
base = "/content/drive/MyDrive/TAKD_models"

def evaluate(model_name, path, dataset):
    if not os.path.exists(path):
        return "MISSING"

    num_classes = 100 if dataset == "cifar100" else 10
    _, test_loader = get_cifar(num_classes)

    model = create_cnn_model(model_name, dataset, use_cuda=(device == "cuda"))
    ckpt = torch.load(path, map_location=device)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()

    correct, total = 0, 0
    with torch.no_grad():
        for x, y in test_loader:
            x, y = x.to(device), y.to(device)
            out = model(x)
            _, pred = torch.max(out, 1)
            total += y.size(0)
            correct += (pred == y).sum().item()

    return round(100.0 * correct / total, 2)

experiments = [
    ("CNN", "CIFAR-10",  "cifar10",  "plane2",  f"{base}/cnn_cifar10_nokd_plane2_best.pth.tar",   f"{base}/cnn_cifar10_blkd_plane2_best.pth.tar",   f"{base}/cnn_cifar10_takd_plane2_best.pth.tar"),
    ("CNN", "CIFAR-100", "cifar100", "plane2",  f"{base}/cnn_cifar100_nokd_plane2_best.pth.tar",  f"{base}/cnn_cifar100_blkd_plane2_best.pth.tar",  f"{base}/cnn_cifar100_takd_plane2_best.pth.tar"),
    ("ResNet", "CIFAR-10",  "cifar10",  "resnet8", f"{base}/resnet_cifar10_nokd_resnet8_best.pth.tar",  f"{base}/resnet_cifar10_blkd_resnet8_best.pth.tar",  f"{base}/resnet_cifar10_takd_resnet8_best.pth.tar"),
    ("ResNet", "CIFAR-100", "cifar100", "resnet8", f"{base}/resnet_cifar100_nokd_resnet8_best.pth.tar", f"{base}/resnet_cifar100_blkd_resnet8_best.pth.tar", f"{base}/resnet_cifar100_takd_resnet8_best.pth.tar"),
]

rows = []
for model, dataset_label, dataset_key, name, nokd, blkd, takd in experiments:
    rows.append({
        "Model": model,
        "Dataset": dataset_label,
        "NOKD": evaluate(name, nokd, dataset_key),
        "BLKD": evaluate(name, blkd, dataset_key),
        "TAKD": evaluate(name, takd, dataset_key)
    })

results_df = pd.DataFrame(rows)

paper_df = pd.DataFrame([
    {"Model": "CNN",    "Dataset": "CIFAR-10",  "NOKD_paper": 70.16, "BLKD_paper": 72.57, "TAKD_paper": 73.51},
    {"Model": "CNN",    "Dataset": "CIFAR-100", "NOKD_paper": 41.09, "BLKD_paper": 44.57, "TAKD_paper": 44.92},
    {"Model": "ResNet", "Dataset": "CIFAR-10",  "NOKD_paper": 88.52, "BLKD_paper": 88.65, "TAKD_paper": 88.98},
    {"Model": "ResNet", "Dataset": "CIFAR-100", "NOKD_paper": 61.37, "BLKD_paper": 61.41, "TAKD_paper": 61.82},
])

final_df = results_df.merge(paper_df, on=["Model", "Dataset"], how="left")

print("\n===== YOUR RESULTS =====")
print(results_df.to_string(index=False))

print("\n===== COMPARISON WITH PAPER =====")
print(final_df.to_string(index=False))

!ls /content/drive/MyDrive/TAKD_models | grep resnet110